#FROM mariadb:10.2

# Копируем скрипт инициализации в контейнер
#COPY sql/init_db.sql /docker-entrypoint-initdb.d/
#COPY sql/data.sql /docker-entrypoint-initdb.d/

# Устанавливаем права на файл
#RUN chmod 644 /docker-entrypoint-initdb.d/init_db.sql
#RUN chmod 644 /docker-entrypoint-initdb.d/data.sql